### ISSUE TITLE
Roofs dont align with the top of the building

### ISSUE THREAD

**Issue by Pleijten-dev** [cityjson/RhinoCityJSON#2]
Hi Love the plugin however with the new update i have encountered a problem with the roofs. The roofs dont align with the top of the buildings (or are not loaded in their entirety), in LOD 2.2 many of the roofs unfortunately dont align to the tops of the buildings. this happens in the case of amongst others 3dbag files: 9-308-520.city.json & 9-312-520.city.json.

![roofs](https://github.com/cityjson/RhinoCityJSON/assets/154469036/6b885b1d-1900-4e8e-828f-6bfcbf8842b7)
![roofs_2](https://github.com/cityjson/RhinoCityJSON/assets/154469036/1340993b-181f-411e-bb30-1d2b28702512)

**Comment by jaspervdv** [comment]
Hello! thanks for submitting an issue

We have not yet been able to pinpoint the actual issue yet. However, the issue seems to be related to the scale that is set in the Rhino file. When the file is set to meters it should not give these issues (to a similar extend). So, until we found the code that is causing the issue this would be a way to avoid it

**Comment by jaspervdv** [comment]
Hello again,

The issue has been found and resolved in the push of today. It will be implemented in a release soon.
